- lib/elixlsx.ex
- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
From what I understand Elixir all values except `false` and `nil` (so including `0`) will evaluate to `true`
[http://elixir-examples.github.io/examples/boolean-operators](http://elixir-examples.github.io/examples/boolean-operators)
Before that, all generated files without set column widths contained empty `<cols></cols>` tags which was treated under windows as wrong xlsx format.
Thanks to @jakubsta !
> Fix col widths

- README.md
- example.exs
- lib/elixlsx/style/font.ex
- lib/elixlsx/xml_templates.ex
I'm missing some alignment functions. This PR will add the `align_horizontal` option.
Available values are `:left`, `:right`, `:center`, `:justify`, `:general`, `:fill`
And I add a hex shield to the README ;-)
> Support horizontal alignment

- lib/elixlsx/xml_templates.ex
warning: Map.size/1 is deprecated, please use Kernel.map_size/1
> Use Kernel.map_size instead of Dict.size

- lib/elixlsx/xml_templates.ex
- test/elixlsx_test.exs
Currently the following is rendered in the XML:
Which results in the following output:
> Fix double escaping issue

- example.exs
- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
> allow to merge cells

- lib/elixlsx/style/border_style.ex
After some experimentation I found that this change resolved the problem I encountered opening files generate by elixlsx in Excel for Mac. See this issue for more detail: https://github.com/xou/elixlsx/issues/17.
I was concerned that this change might break other Excel editors. I couldn't find a schema definition that seemed relevant so I created a simple spreadsheet in Google Sheets. I exported the Google Sheet as xlsx, extracted the content and took a look at styles.xml. This is the relevant part I found:
```
<borders count="1">
<border>
<left/>
<right/>
<top/>
<bottom/>
</border>
</borders>
```
Seeing that Google Sheets exports xlsx files with the borders ordered left, right, top, bottom as proposed in my PR gave me confidence that this ordering is likely the most compatible if it's …
> Change border style to resolve Excel for Mac issue

- mix.exs
I'm getting warnings when running my own app code from the bareword function calls inside this library's `mix.exs`. Fixed in this pull request. There may be other locations where this fix needs to be made, but at least this will stop some pesky warnings.
> Fix some Elixir 1.4 warnings (barewords)

- example.exs
- lib/elixlsx/compiler/fill_db.ex
- lib/elixlsx/util.ex
- lib/elixlsx/xml_templates.ex
Sorry for the long waiting time, I had some trouble with my computer..
At first I added the formula content type (issue #16). This can be used with `Sheet.set_cell("XY", {:formula, "FUNCTION"})`. I add some examples to the file. 
I noticed only a problem with the `Util.to_excel_datetime/1` function. Are here other functions to check with the new function?
On last commit I fix an issue with background color on Microsoft Excel. The first and second colors are reserved and can not overriden. 
I hope I did not forget anything.
Tested on:
Microsoft Excel for Mac 15.30 (current version)
Libre Office 5.2.5.1 on Mac
Numbers 4.0.5 on Mac
> Formula support & Fix background issue 

- example.exs
- lib/elixlsx/xml_templates.ex
The missing commits for issue #16 contain
- Add the `fullCalcOnLoad` value
- Allow default values on formulas
I think we should add a description for the topic default-value anywhere, but I'm not sure which place should be good for this and how describe the problematic simple.
Followed calls are now valid:
`Sheet.set_cell("XY", {:formula, "SUM(1,2,3)"})`
`Sheet.set_cell("XY", {:formula, "SUM(1,2,3)", value: "6"})`
Tested behavior with default value:
Microsoft Excel: Calcluate
Libre Office: **NOT** Calculate
Numbers: Calculate
Tested on:
Microsoft Excel for Mac 15.31
Libre Office 5.2.5.1 on Mac
Numbers 4.0.5 on Mac
> Formula default value

- lib/elixlsx/compiler/fill_db.ex
When issue with background cell styles in Excel was fixed a new bug was introduced that accidentally increased the `element_count` in `filldb` with 2 making every addition count as two. This resulted in sheets with multiple backgrounds styles only the ones indexing at a multiple of two actually got applied (however wrongly), the rest was left without styling.
This fixes the `element_count` to only count each new addition as one. Verified to work in both Excel and LibreOffice.
> Fix filldb index

- lib/elixlsx/util.ex
- lib/elixlsx/xml_templates.ex
This should fix #26 (Excel on mac complains about invalid file), and that the appversion tag was hardcoded at 0.0.6.
The problem seems to be that only one "dot" is allowed in the AppVersion tag. This commit takes the current version from mix.exs and removes the second dot.
> Fix "repair file" bug due to invalid (and stale) AppVersion tag.

- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
- test/elixlsx_test.exs
Hey, here the solution for issue #28.
Microsoft's Excel allows only sheet names with maximal length of 31 chars. The most libraries throws an exception if the name is longer than 31 chars. I think this is the best solution to handle this.
- Added validation and error
- Added test case
- Added info to documentation
> Sheet name length validation

- example.exs
- lib/elixlsx/xml_templates.ex
I wanted to be able to format cells only - without any content. I suggested in this fork supporting a content atom value of :empty to do this. The change to the XMLTemplate logic was simple to detect this and not generate the unneeded <v> element.
> Support cells with content of :empty to allow easier formatting.

- lib/elixlsx/util.ex
Benchmark looks like this
```
Settings:
duration:      1.0 s
[16:12:47] 1/2: mine
[16:12:52] 2/2: original
Finished in 7.01 seconds
benchmark iterations   average time 
mine        10000000   0.46 µs/op
original      100000   17.00 µs/op
```
> Making encode_col loads faster

- mix.lock
- test/elixlsx_test.exs
* Upgrades excheck to 0.5.3
This upgrade is necessary because as of Elixir 
1.4, all ExUnit CLI formatters must use the 
GenServer API (instead of the former GenEvent API)
. Newer versions of this lib account for this 
change.
* Agnostic parsing of content with escaped values
:xmerl_scan parses inner text with escaped values
(like ampersand) in different ways depending on 
the version of the runtime. In older versions, 
the parser splits on the escaped value. This
commit refactors the test to turn this part of the
test agnostic.
> Fixes for compatibility with Elixir 1.5 / OTP 20.0

- lib/elixlsx/xml_templates.ex
The absence of this attribute was raising some issues when opening an archive created with this lib in the `Xlsxir` lib.
Apparently adding it does not affect both tests and generated files.
> Added `numFmtId` attribute to the `xf` elements

- lib/elixlsx.ex
- lib/elixlsx/compiler/workbook_comp_info.ex
- lib/elixlsx/sheet.ex
- lib/elixlsx/workbook.ex
- lib/elixlsx/writer.ex
- mix.exs
- mix.lock
Hi, thanks for creating Elixlsx!
These changes gets elixlsx passing dialyzer on my development environment.
The important changes for my project are the `Elixlsx.write_to` and `Elixlsx.write_to_memory`, since dialyzer warns that calls into these functions will never return, forcing me to suppress the warning in my project.
> Fix dialyzer warnings

- example.exs
- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
Suggesting this patch to support turning off the grid lines on a worksheet. Default is to leave the current behavior, but adding the new show_grid_lines: false to the sheet structure allows an override.
> Add additional control for showGridLines

- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
we can't use bottomRight in every case because spec (ISO/IEC
29500-1:2016) forbids using bottomRight when only one split
(horizontal or vertical) is applied
for horizontal split proper values are bottomLeft and topLeft
for vertical split proper values are topLeft and topRight
also MS Word for Mac OS display 'corrupted document' notification when
only horizontal split is applied, and bottomRight pane is set
fixes #54
> fix pane in sheetView

- lib/elixlsx/xml_templates.ex
Fix for #52.
Escaping special chars in sheet name. The number of chars that be allowed are not affected (tested on macOS).
> Escaping sheet name

- .travis.yml
- README.md
- lib/elixlsx/xml_templates.ex
- mix.exs
- test/elixlsx_test.exs
- test/util_test.exs
@goravbhootra FYI, I'm lowering the required version to 1.3 as 1.3 is the newest version available in Ubuntu and it seems to address the warnings emitted by elixir 1.1. Let me know if you have concerns.
> Downgrade required elixir version for travis test

- example.exs
- lib/elixlsx/xml_templates.ex
Google Docs and Office Online display value properly. Calc shows 1 or 0. OOC itself uses special number format for boolean fields to support localized values: 
```xml
<numFmt numFmtId="169" formatCode="&quot;TRUE&quot;;&quot;TRUE&quot;;&quot;FALSE&quot;"/>
```
Most xlsx-libraries I found ignore it.
> Basic support for boolean values in cells. Fixes #65

- example.exs
- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
Hi. Thank you for providing this wonderful library, which is so simple to use! (I also use Python's openpyxl, but tired of its messy API...)
I personally had a work where I had to group rows/columns, just like the following article:
https://oxen.tech/blog/grouping-excel/
I forked xlixlsx and made some changes to do this.
I'd appreciate it if you review and merge my changes so that everyone can use this feature via Hex!
Your comments and edits are very appreciated.
> row/col outline level (grouping) support

- lib/elixlsx/compiler/cell_style_db.ex
This pull request does not change any functionality. It attempts to make the register_all function in Compiler.CellStyleDB easier to understand and extend.
> improve readability of register_all fn

- lib/elixlsx/util.ex
The module attribute @col_alphabet is a charlist, which is converted to a binary using to_string/1. However, in decode_col_/1, it is converted back to a charlist before being used. It is never used in its binary form. The removal of the redundant conversions, which has no change in functionality, increases the speed of decode_col_/1 by about 10% (measured with Benchee).
If a string is passed as an arg to decode_col, it is checked using String.valid? and String.match?. The elimination of the first check using guard clauses, which has no change in functionality, increases the speed of decode_col/1 by about another 10% (for string args, with no change in speed for charlist args).
The if clause has been changed to a case clause to make the code paths more clear, with no change in logic.
> cleaner, faster code in decode_col fn

- lib/elixlsx/util.ex
`encode_col/1` recursively calls itself twice when `num` is > 26. This can be avoided by building up the encoded string and passing into each recursive call. This increases the speed of encoding a column number by around 100% (when measured with Benchee). There is no change in functionality.
> avoid unnecessary encode_col calls

- mix.exs
- mix.lock
The triq package is hosted on hex (latest version 1.3), so there is no need to get the dependency from a git repository.
> get triq dep from hex

- lib/elixlsx/xml_templates.ex
The function has been made more readable using pattern matching. The functionality has not been changed.
The revised function runs about 3% faster when measured with Benchee.
> refactor split_into_content_style/2 to make it more readable

- lib/elixlsx/compiler.ex
- lib/elixlsx/compiler/string_db.ex
- lib/elixlsx/style/num_fmt.ex
- lib/elixlsx/util.ex
- lib/elixlsx/xml.ex
- lib/elixlsx/xml_templates.ex
- test/xml_test.exs
We also ran across special characters that aren't valid xml characters.
> XML Validation

- lib/elixlsx/sheet.ex
When using Dialyzer to check code that depends on elixlsx, we noticed that the type checker fails if you include values in the `merge_cells` parameter of a new `%Sheet{}`. It looks like the `merge_cells` input is expecting `[]`, meaning an empty array, so any included params will throw an error. 
This PR will allow a user to pass tuples of cells to merge as demonstrated in the `example.exs` file, or an empty array if they do not supply a `merge_cells` param, and not fail Dialyzer type checking either way. 
Thanks for the great XLS package!
> allow values to be present in merge_cells array in Sheet type

- .formatter.exs
- lib/elixlsx/xml_templates.ex
- mix.exs
- test/elixlsx_test.exs
- test/test_helper.exs
- test/util_test.exs
Add blank and invalid characters validation in sheet name.
And I found the length of sheet name validation using `String.length/1` currently. This will fail when non-ASCII characters contain in sheet name because it counting by Unicode graphemes but not byte size. And I found the length of sheet name in Excel 16.16.14 on Mac seems to calculate by counting UCS-2 points or this in Elixir:
```Elixir
"😂" |> :unicode.characters_to_binary(:utf8, :utf16) |> byte_size() |> div(2)
```
Should I also fix the length validation?
> Improve sheet name validation

- lib/elixlsx/xml_templates.ex
Currently if you try to add leading whitespace to a cell it gets stripped out. I've modified the code to add the `xml:space="preserve"` attribute to the strings sharedStrings database which addresses this.
> adds preserve spaces XML attribute

- lib/elixlsx/util.ex
Fixes compiler warnings emitted by elixir 1.11
> compile(@doc): Combine documentation for to_excel_datetime into one call

- lib/elixlsx/compiler.ex
- lib/elixlsx/compiler/string_db.ex
- lib/elixlsx/style/num_fmt.ex
- lib/elixlsx/util.ex
- lib/elixlsx/xml.ex
- test/xml_test.exs
Per this issue: #107 
We've been unable to update elixlsx due to the top-level XML module introduced in #86.
This pr seeks to namespace that module to match the usual practice and adds aliases as necessary
> namespace xml module

- example.exs
- lib/elixlsx/sheet.ex
- lib/elixlsx/xml_templates.ex
This PR adds support for the [validations dropdown feature from Excel](https://support.microsoft.com/en-us/office/apply-data-validation-to-cells-29fecbcc-d1b9-42c1-9d76-eff3ce5f7249). 
More info about `DataValidation` tag can be found [here](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.datavalidation?view=openxml-2.8.1).
> Add cells validators
